import type { SportConfig, TeamInfo, Conference, StatCategory } from '@dynasty-os/core-types';

const teams: TeamInfo[] = [
  // SEC
  { name: 'Alabama Crimson Tide', abbreviation: 'ALA', conference: 'SEC', mascot: 'Crimson Tide' },
  { name: 'Arkansas Razorbacks', abbreviation: 'ARK', conference: 'SEC', mascot: 'Razorbacks' },
  { name: 'Auburn Tigers', abbreviation: 'AUB', conference: 'SEC', mascot: 'Tigers' },
  { name: 'Florida Gators', abbreviation: 'FLA', conference: 'SEC', mascot: 'Gators' },
  { name: 'Georgia Bulldogs', abbreviation: 'UGA', conference: 'SEC', mascot: 'Bulldogs' },
  { name: 'Kentucky Wildcats', abbreviation: 'KEN', conference: 'SEC', mascot: 'Wildcats' },
  { name: 'LSU Tigers', abbreviation: 'LSU', conference: 'SEC', mascot: 'Tigers' },
  { name: 'Mississippi State Bulldogs', abbreviation: 'MSST', conference: 'SEC', mascot: 'Bulldogs' },
  { name: 'Missouri Tigers', abbreviation: 'MIZ', conference: 'SEC', mascot: 'Tigers' },
  { name: 'Oklahoma Sooners', abbreviation: 'OU', conference: 'SEC', mascot: 'Sooners' },
  { name: 'Ole Miss Rebels', abbreviation: 'MISS', conference: 'SEC', mascot: 'Rebels' },
  { name: 'South Carolina Gamecocks', abbreviation: 'SC', conference: 'SEC', mascot: 'Gamecocks' },
  { name: 'Tennessee Volunteers', abbreviation: 'TENN', conference: 'SEC', mascot: 'Volunteers' },
  { name: 'Texas Longhorns', abbreviation: 'TEX', conference: 'SEC', mascot: 'Longhorns' },
  { name: 'Texas A&M Aggies', abbreviation: 'TAMU', conference: 'SEC', mascot: 'Aggies' },
  { name: 'Vanderbilt Commodores', abbreviation: 'VAN', conference: 'SEC', mascot: 'Commodores' },
  // Big Ten
  { name: 'Illinois Fighting Illini', abbreviation: 'ILL', conference: 'Big Ten', mascot: 'Fighting Illini' },
  { name: 'Indiana Hoosiers', abbreviation: 'IND', conference: 'Big Ten', mascot: 'Hoosiers' },
  { name: 'Iowa Hawkeyes', abbreviation: 'IOWA', conference: 'Big Ten', mascot: 'Hawkeyes' },
  { name: 'Maryland Terrapins', abbreviation: 'MD', conference: 'Big Ten', mascot: 'Terrapins' },
  { name: 'Michigan Wolverines', abbreviation: 'MICH', conference: 'Big Ten', mascot: 'Wolverines' },
  { name: 'Michigan State Spartans', abbreviation: 'MSU', conference: 'Big Ten', mascot: 'Spartans' },
  { name: 'Minnesota Golden Gophers', abbreviation: 'MINN', conference: 'Big Ten', mascot: 'Golden Gophers' },
  { name: 'Nebraska Cornhuskers', abbreviation: 'NEB', conference: 'Big Ten', mascot: 'Cornhuskers' },
  { name: 'Northwestern Wildcats', abbreviation: 'NW', conference: 'Big Ten', mascot: 'Wildcats' },
  { name: 'Ohio State Buckeyes', abbreviation: 'OSU', conference: 'Big Ten', mascot: 'Buckeyes' },
  { name: 'Oregon Ducks', abbreviation: 'ORE', conference: 'Big Ten', mascot: 'Ducks' },
  { name: 'Penn State Nittany Lions', abbreviation: 'PSU', conference: 'Big Ten', mascot: 'Nittany Lions' },
  { name: 'Purdue Boilermakers', abbreviation: 'PUR', conference: 'Big Ten', mascot: 'Boilermakers' },
  { name: 'Rutgers Scarlet Knights', abbreviation: 'RUT', conference: 'Big Ten', mascot: 'Scarlet Knights' },
  { name: 'UCLA Bruins', abbreviation: 'UCLA', conference: 'Big Ten', mascot: 'Bruins' },
  { name: 'USC Trojans', abbreviation: 'USC', conference: 'Big Ten', mascot: 'Trojans' },
  { name: 'Washington Huskies', abbreviation: 'WASH', conference: 'Big Ten', mascot: 'Huskies' },
  { name: 'Wisconsin Badgers', abbreviation: 'WIS', conference: 'Big Ten', mascot: 'Badgers' },
  // Big 12
  { name: 'Arizona Wildcats', abbreviation: 'ARIZ', conference: 'Big 12', mascot: 'Wildcats' },
  { name: 'Arizona State Sun Devils', abbreviation: 'ASU', conference: 'Big 12', mascot: 'Sun Devils' },
  { name: 'Baylor Bears', abbreviation: 'BAY', conference: 'Big 12', mascot: 'Bears' },
  { name: 'BYU Cougars', abbreviation: 'BYU', conference: 'Big 12', mascot: 'Cougars' },
  { name: 'Cincinnati Bearcats', abbreviation: 'CIN', conference: 'Big 12', mascot: 'Bearcats' },
  { name: 'Colorado Buffaloes', abbreviation: 'COL', conference: 'Big 12', mascot: 'Buffaloes' },
  { name: 'Houston Cougars', abbreviation: 'HOU', conference: 'Big 12', mascot: 'Cougars' },
  { name: 'Iowa State Cyclones', abbreviation: 'ISU', conference: 'Big 12', mascot: 'Cyclones' },
  { name: 'Kansas Jayhawks', abbreviation: 'KU', conference: 'Big 12', mascot: 'Jayhawks' },
  { name: 'Kansas State Wildcats', abbreviation: 'KSU', conference: 'Big 12', mascot: 'Wildcats' },
  { name: 'Oklahoma State Cowboys', abbreviation: 'OKST', conference: 'Big 12', mascot: 'Cowboys' },
  { name: 'TCU Horned Frogs', abbreviation: 'TCU', conference: 'Big 12', mascot: 'Horned Frogs' },
  { name: 'Texas Tech Red Raiders', abbreviation: 'TTU', conference: 'Big 12', mascot: 'Red Raiders' },
  { name: 'UCF Knights', abbreviation: 'UCF', conference: 'Big 12', mascot: 'Knights' },
  { name: 'Utah Utes', abbreviation: 'UTAH', conference: 'Big 12', mascot: 'Utes' },
  { name: 'West Virginia Mountaineers', abbreviation: 'WVU', conference: 'Big 12', mascot: 'Mountaineers' },
  // ACC
  { name: 'Boston College Eagles', abbreviation: 'BC', conference: 'ACC', mascot: 'Eagles' },
  { name: 'California Golden Bears', abbreviation: 'CAL', conference: 'ACC', mascot: 'Golden Bears' },
  { name: 'Clemson Tigers', abbreviation: 'CLEM', conference: 'ACC', mascot: 'Tigers' },
  { name: 'Duke Blue Devils', abbreviation: 'DUKE', conference: 'ACC', mascot: 'Blue Devils' },
  { name: 'Florida State Seminoles', abbreviation: 'FSU', conference: 'ACC', mascot: 'Seminoles' },
  { name: 'Georgia Tech Yellow Jackets', abbreviation: 'GT', conference: 'ACC', mascot: 'Yellow Jackets' },
  { name: 'Louisville Cardinals', abbreviation: 'LOU', conference: 'ACC', mascot: 'Cardinals' },
  { name: 'Miami Hurricanes', abbreviation: 'MIA', conference: 'ACC', mascot: 'Hurricanes' },
  { name: 'NC State Wolfpack', abbreviation: 'NCST', conference: 'ACC', mascot: 'Wolfpack' },
  { name: 'North Carolina Tar Heels', abbreviation: 'UNC', conference: 'ACC', mascot: 'Tar Heels' },
  { name: 'Pittsburgh Panthers', abbreviation: 'PITT', conference: 'ACC', mascot: 'Panthers' },
  { name: 'SMU Mustangs', abbreviation: 'SMU', conference: 'ACC', mascot: 'Mustangs' },
  { name: 'Stanford Cardinal', abbreviation: 'STAN', conference: 'ACC', mascot: 'Cardinal' },
  { name: 'Syracuse Orange', abbreviation: 'SYR', conference: 'ACC', mascot: 'Orange' },
  { name: 'Virginia Cavaliers', abbreviation: 'UVA', conference: 'ACC', mascot: 'Cavaliers' },
  { name: 'Virginia Tech Hokies', abbreviation: 'VT', conference: 'ACC', mascot: 'Hokies' },
  { name: 'Wake Forest Demon Deacons', abbreviation: 'WAKE', conference: 'ACC', mascot: 'Demon Deacons' },
  // American Athletic Conference (AAC)
  { name: 'Charlotte 49ers', abbreviation: 'CHAR', conference: 'AAC', mascot: '49ers' },
  { name: 'East Carolina Pirates', abbreviation: 'ECU', conference: 'AAC', mascot: 'Pirates' },
  { name: 'FAU Owls', abbreviation: 'FAU', conference: 'AAC', mascot: 'Owls' },
  { name: 'Memphis Tigers', abbreviation: 'MEM', conference: 'AAC', mascot: 'Tigers' },
  { name: 'Navy Midshipmen', abbreviation: 'NAVY', conference: 'AAC', mascot: 'Midshipmen' },
  { name: 'North Texas Mean Green', abbreviation: 'UNT', conference: 'AAC', mascot: 'Mean Green' },
  { name: 'Rice Owls', abbreviation: 'RICE', conference: 'AAC', mascot: 'Owls' },
  { name: 'South Florida Bulls', abbreviation: 'USF', conference: 'AAC', mascot: 'Bulls' },
  { name: 'Temple Owls', abbreviation: 'TEM', conference: 'AAC', mascot: 'Owls' },
  { name: 'Tulane Green Wave', abbreviation: 'TUL', conference: 'AAC', mascot: 'Green Wave' },
  { name: 'Tulsa Golden Hurricane', abbreviation: 'TLSA', conference: 'AAC', mascot: 'Golden Hurricane' },
  { name: 'UTSA Roadrunners', abbreviation: 'UTSA', conference: 'AAC', mascot: 'Roadrunners' },
  { name: 'Wichita State Shockers', abbreviation: 'WICH', conference: 'AAC', mascot: 'Shockers' },
  // Sun Belt
  { name: 'App State Mountaineers', abbreviation: 'APP', conference: 'Sun Belt', mascot: 'Mountaineers' },
  { name: 'Arkansas State Red Wolves', abbreviation: 'ARST', conference: 'Sun Belt', mascot: 'Red Wolves' },
  { name: 'Coastal Carolina Chanticleers', abbreviation: 'CCU', conference: 'Sun Belt', mascot: 'Chanticleers' },
  { name: 'Georgia Southern Eagles', abbreviation: 'GASO', conference: 'Sun Belt', mascot: 'Eagles' },
  { name: 'Georgia State Panthers', abbreviation: 'GAST', conference: 'Sun Belt', mascot: 'Panthers' },
  { name: 'James Madison Dukes', abbreviation: 'JMU', conference: 'Sun Belt', mascot: 'Dukes' },
  { name: 'Louisiana Ragin Cajuns', abbreviation: 'ULL', conference: 'Sun Belt', mascot: 'Ragin Cajuns' },
  { name: 'Louisiana Monroe Warhawks', abbreviation: 'ULM', conference: 'Sun Belt', mascot: 'Warhawks' },
  { name: 'Marshall Thundering Herd', abbreviation: 'MRSH', conference: 'Sun Belt', mascot: 'Thundering Herd' },
  { name: 'Old Dominion Monarchs', abbreviation: 'ODU', conference: 'Sun Belt', mascot: 'Monarchs' },
  { name: 'South Alabama Jaguars', abbreviation: 'SOAL', conference: 'Sun Belt', mascot: 'Jaguars' },
  { name: 'Southern Miss Golden Eagles', abbreviation: 'USM', conference: 'Sun Belt', mascot: 'Golden Eagles' },
  { name: 'Texas State Bobcats', abbreviation: 'TXST', conference: 'Sun Belt', mascot: 'Bobcats' },
  { name: 'Troy Trojans', abbreviation: 'TROY', conference: 'Sun Belt', mascot: 'Trojans' },
  // Conference USA (C-USA)
  { name: 'FIU Panthers', abbreviation: 'FIU', conference: 'C-USA', mascot: 'Panthers' },
  { name: 'Jacksonville State Gamecocks', abbreviation: 'JVST', conference: 'C-USA', mascot: 'Gamecocks' },
  { name: 'Kennesaw State Owls', abbreviation: 'KENN', conference: 'C-USA', mascot: 'Owls' },
  { name: 'Liberty Flames', abbreviation: 'LIB', conference: 'C-USA', mascot: 'Flames' },
  { name: 'Louisiana Tech Bulldogs', abbreviation: 'LT', conference: 'C-USA', mascot: 'Bulldogs' },
  { name: 'Middle Tennessee Blue Raiders', abbreviation: 'MTSU', conference: 'C-USA', mascot: 'Blue Raiders' },
  { name: 'New Mexico State Aggies', abbreviation: 'NMSU', conference: 'C-USA', mascot: 'Aggies' },
  { name: 'Sam Houston Bearkats', abbreviation: 'SHSU', conference: 'C-USA', mascot: 'Bearkats' },
  { name: 'UTEP Miners', abbreviation: 'UTEP', conference: 'C-USA', mascot: 'Miners' },
  { name: 'Western Kentucky Hilltoppers', abbreviation: 'WKU', conference: 'C-USA', mascot: 'Hilltoppers' },
  // MAC
  { name: 'Akron Zips', abbreviation: 'AKR', conference: 'MAC', mascot: 'Zips' },
  { name: 'Ball State Cardinals', abbreviation: 'BALL', conference: 'MAC', mascot: 'Cardinals' },
  { name: 'Bowling Green Falcons', abbreviation: 'BGSU', conference: 'MAC', mascot: 'Falcons' },
  { name: 'Buffalo Bulls', abbreviation: 'BUFF', conference: 'MAC', mascot: 'Bulls' },
  { name: 'Central Michigan Chippewas', abbreviation: 'CMU', conference: 'MAC', mascot: 'Chippewas' },
  { name: 'Eastern Michigan Eagles', abbreviation: 'EMU', conference: 'MAC', mascot: 'Eagles' },
  { name: 'Kent State Golden Flashes', abbreviation: 'KENT', conference: 'MAC', mascot: 'Golden Flashes' },
  { name: 'Miami (OH) RedHawks', abbreviation: 'MIOH', conference: 'MAC', mascot: 'RedHawks' },
  { name: 'Northern Illinois Huskies', abbreviation: 'NIU', conference: 'MAC', mascot: 'Huskies' },
  { name: 'Ohio Bobcats', abbreviation: 'OHIO', conference: 'MAC', mascot: 'Bobcats' },
  { name: 'Toledo Rockets', abbreviation: 'TOL', conference: 'MAC', mascot: 'Rockets' },
  { name: 'Western Michigan Broncos', abbreviation: 'WMU', conference: 'MAC', mascot: 'Broncos' },
  // Mountain West
  { name: 'Air Force Falcons', abbreviation: 'AF', conference: 'Mountain West', mascot: 'Falcons' },
  { name: 'Boise State Broncos', abbreviation: 'BSU', conference: 'Mountain West', mascot: 'Broncos' },
  { name: 'Colorado State Rams', abbreviation: 'CSU', conference: 'Mountain West', mascot: 'Rams' },
  { name: 'Fresno State Bulldogs', abbreviation: 'FRES', conference: 'Mountain West', mascot: 'Bulldogs' },
  { name: 'Hawaii Rainbow Warriors', abbreviation: 'HAW', conference: 'Mountain West', mascot: 'Rainbow Warriors' },
  { name: 'Nevada Wolf Pack', abbreviation: 'NEV', conference: 'Mountain West', mascot: 'Wolf Pack' },
  { name: 'New Mexico Lobos', abbreviation: 'UNM', conference: 'Mountain West', mascot: 'Lobos' },
  { name: 'San Diego State Aztecs', abbreviation: 'SDSU', conference: 'Mountain West', mascot: 'Aztecs' },
  { name: 'San Jose State Spartans', abbreviation: 'SJSU', conference: 'Mountain West', mascot: 'Spartans' },
  { name: 'UNLV Rebels', abbreviation: 'UNLV', conference: 'Mountain West', mascot: 'Rebels' },
  { name: 'Utah State Aggies', abbreviation: 'UTST', conference: 'Mountain West', mascot: 'Aggies' },
  { name: 'Wyoming Cowboys', abbreviation: 'WYO', conference: 'Mountain West', mascot: 'Cowboys' },
  // Independents
  { name: 'Notre Dame Fighting Irish', abbreviation: 'ND', conference: 'Independent', mascot: 'Fighting Irish' },
  { name: 'Army Black Knights', abbreviation: 'ARMY', conference: 'Independent', mascot: 'Black Knights' },
  { name: 'Connecticut Huskies', abbreviation: 'UCONN', conference: 'Independent', mascot: 'Huskies' },
  { name: 'UMass Minutemen', abbreviation: 'MASS', conference: 'Independent', mascot: 'Minutemen' },
];

const conferences: Conference[] = [
  {
    name: 'SEC',
    teams: ['Alabama Crimson Tide', 'Arkansas Razorbacks', 'Auburn Tigers', 'Florida Gators', 'Georgia Bulldogs', 'Kentucky Wildcats', 'LSU Tigers', 'Mississippi State Bulldogs', 'Missouri Tigers', 'Oklahoma Sooners', 'Ole Miss Rebels', 'South Carolina Gamecocks', 'Tennessee Volunteers', 'Texas Longhorns', 'Texas A&M Aggies', 'Vanderbilt Commodores'],
  },
  {
    name: 'Big Ten',
    teams: ['Illinois Fighting Illini', 'Indiana Hoosiers', 'Iowa Hawkeyes', 'Maryland Terrapins', 'Michigan Wolverines', 'Michigan State Spartans', 'Minnesota Golden Gophers', 'Nebraska Cornhuskers', 'Northwestern Wildcats', 'Ohio State Buckeyes', 'Oregon Ducks', 'Penn State Nittany Lions', 'Purdue Boilermakers', 'Rutgers Scarlet Knights', 'UCLA Bruins', 'USC Trojans', 'Washington Huskies', 'Wisconsin Badgers'],
  },
  {
    name: 'Big 12',
    teams: ['Arizona Wildcats', 'Arizona State Sun Devils', 'Baylor Bears', 'BYU Cougars', 'Cincinnati Bearcats', 'Colorado Buffaloes', 'Houston Cougars', 'Iowa State Cyclones', 'Kansas Jayhawks', 'Kansas State Wildcats', 'Oklahoma State Cowboys', 'TCU Horned Frogs', 'Texas Tech Red Raiders', 'UCF Knights', 'Utah Utes', 'West Virginia Mountaineers'],
  },
  {
    name: 'ACC',
    teams: ['Boston College Eagles', 'California Golden Bears', 'Clemson Tigers', 'Duke Blue Devils', 'Florida State Seminoles', 'Georgia Tech Yellow Jackets', 'Louisville Cardinals', 'Miami Hurricanes', 'NC State Wolfpack', 'North Carolina Tar Heels', 'Pittsburgh Panthers', 'SMU Mustangs', 'Stanford Cardinal', 'Syracuse Orange', 'Virginia Cavaliers', 'Virginia Tech Hokies', 'Wake Forest Demon Deacons'],
  },
  {
    name: 'AAC',
    teams: ['Charlotte 49ers', 'East Carolina Pirates', 'FAU Owls', 'Memphis Tigers', 'Navy Midshipmen', 'North Texas Mean Green', 'Rice Owls', 'South Florida Bulls', 'Temple Owls', 'Tulane Green Wave', 'Tulsa Golden Hurricane', 'UTSA Roadrunners', 'Wichita State Shockers'],
  },
  {
    name: 'Sun Belt',
    teams: ['App State Mountaineers', 'Arkansas State Red Wolves', 'Coastal Carolina Chanticleers', 'Georgia Southern Eagles', 'Georgia State Panthers', 'James Madison Dukes', 'Louisiana Ragin Cajuns', 'Louisiana Monroe Warhawks', 'Marshall Thundering Herd', 'Old Dominion Monarchs', 'South Alabama Jaguars', 'Southern Miss Golden Eagles', 'Texas State Bobcats', 'Troy Trojans'],
  },
  {
    name: 'C-USA',
    teams: ['FIU Panthers', 'Jacksonville State Gamecocks', 'Kennesaw State Owls', 'Liberty Flames', 'Louisiana Tech Bulldogs', 'Middle Tennessee Blue Raiders', 'New Mexico State Aggies', 'Sam Houston Bearkats', 'UTEP Miners', 'Western Kentucky Hilltoppers'],
  },
  {
    name: 'MAC',
    teams: ['Akron Zips', 'Ball State Cardinals', 'Bowling Green Falcons', 'Buffalo Bulls', 'Central Michigan Chippewas', 'Eastern Michigan Eagles', 'Kent State Golden Flashes', 'Miami (OH) RedHawks', 'Northern Illinois Huskies', 'Ohio Bobcats', 'Toledo Rockets', 'Western Michigan Broncos'],
  },
  {
    name: 'Mountain West',
    teams: ['Air Force Falcons', 'Boise State Broncos', 'Colorado State Rams', 'Fresno State Bulldogs', 'Hawaii Rainbow Warriors', 'Nevada Wolf Pack', 'New Mexico Lobos', 'San Diego State Aztecs', 'San Jose State Spartans', 'UNLV Rebels', 'Utah State Aggies', 'Wyoming Cowboys'],
  },
  {
    name: 'Independent',
    teams: ['Notre Dame Fighting Irish', 'Army Black Knights', 'Connecticut Huskies', 'UMass Minutemen'],
  },
];

const statCategories: StatCategory[] = [
  // Passing
  { key: 'passingYards', label: 'Passing Yards', group: 'Passing', type: 'integer' },
  { key: 'passingTDs', label: 'Passing TDs', group: 'Passing', type: 'integer' },
  { key: 'interceptions', label: 'Interceptions', group: 'Passing', type: 'integer' },
  { key: 'completions', label: 'Completions', group: 'Passing', type: 'integer' },
  { key: 'attempts', label: 'Attempts', group: 'Passing', type: 'integer' },
  { key: 'passerRating', label: 'Passer Rating', group: 'Passing', type: 'decimal' },
  // Rushing
  { key: 'rushingYards', label: 'Rushing Yards', group: 'Rushing', type: 'integer' },
  { key: 'rushingTDs', label: 'Rushing TDs', group: 'Rushing', type: 'integer' },
  { key: 'rushingAttempts', label: 'Rushing Attempts', group: 'Rushing', type: 'integer' },
  // Receiving
  { key: 'receivingYards', label: 'Receiving Yards', group: 'Receiving', type: 'integer' },
  { key: 'receivingTDs', label: 'Receiving TDs', group: 'Receiving', type: 'integer' },
  { key: 'receptions', label: 'Receptions', group: 'Receiving', type: 'integer' },
  // Defense
  { key: 'tackles', label: 'Tackles', group: 'Defense', type: 'integer' },
  { key: 'sacks', label: 'Sacks', group: 'Defense', type: 'decimal' },
  { key: 'defenseInterceptions', label: 'Interceptions', group: 'Defense', type: 'integer' },
  { key: 'forcedFumbles', label: 'Forced Fumbles', group: 'Defense', type: 'integer' },
  { key: 'passDeflections', label: 'Pass Deflections', group: 'Defense', type: 'integer' },
  // Special Teams
  { key: 'fgMade', label: 'FG Made', group: 'Special Teams', type: 'integer' },
  { key: 'fgAttempted', label: 'FG Attempted', group: 'Special Teams', type: 'integer' },
  { key: 'punts', label: 'Punts', group: 'Special Teams', type: 'integer' },
  { key: 'puntAverage', label: 'Punt Average', group: 'Special Teams', type: 'decimal' },
  // General
  { key: 'gamesPlayed', label: 'Games Played', group: 'General', type: 'integer' },
];

export const cfbConfig: SportConfig = {
  sport: 'cfb',
  label: 'College Football',
  teams,
  conferences,
  positions: ['QB', 'RB', 'WR', 'TE', 'OL', 'DL', 'LB', 'CB', 'S', 'K', 'P', 'ATH'],
  statCategories,
  gameTypes: ['regular', 'conference', 'bowl', 'playoff'],
  rankingSystems: ['AP', 'CFP'],
  classYears: ['FR', 'SO', 'JR', 'SR', 'RS-FR', 'RS-SO', 'RS-JR', 'RS-SR'],
  gameVersions: ['EA Sports CFB 25', 'EA Sports CFB 26'],
};
