// ESPN numeric team IDs for NCAA football logos
// URL format: https://a.espncdn.com/i/teamlogos/ncaa/500/{id}.png

export const CFB_ESPN_IDS: Record<string, number> = {
  // SEC
  'Alabama Crimson Tide': 333,
  'Arkansas Razorbacks': 8,
  'Auburn Tigers': 2,
  'Florida Gators': 57,
  'Georgia Bulldogs': 61,
  'Kentucky Wildcats': 96,
  'LSU Tigers': 99,
  'Mississippi State Bulldogs': 344,
  'Missouri Tigers': 142,
  'Oklahoma Sooners': 201,
  'Ole Miss Rebels': 145,
  'South Carolina Gamecocks': 2579,
  'Tennessee Volunteers': 2633,
  'Texas Longhorns': 251,
  'Texas A&M Aggies': 245,
  'Vanderbilt Commodores': 238,
  // Big Ten
  'Illinois Fighting Illini': 356,
  'Indiana Hoosiers': 84,
  'Iowa Hawkeyes': 2294,
  'Maryland Terrapins': 120,
  'Michigan Wolverines': 130,
  'Michigan State Spartans': 127,
  'Minnesota Golden Gophers': 135,
  'Nebraska Cornhuskers': 158,
  'Northwestern Wildcats': 77,
  'Ohio State Buckeyes': 194,
  'Oregon Ducks': 2483,
  'Penn State Nittany Lions': 213,
  'Purdue Boilermakers': 2509,
  'Rutgers Scarlet Knights': 164,
  'UCLA Bruins': 26,
  'USC Trojans': 30,
  'Washington Huskies': 264,
  'Wisconsin Badgers': 275,
  // Big 12
  'Arizona Wildcats': 12,
  'Arizona State Sun Devils': 9,
  'Baylor Bears': 239,
  'BYU Cougars': 252,
  'Cincinnati Bearcats': 2132,
  'Colorado Buffaloes': 38,
  'Houston Cougars': 248,
  'Iowa State Cyclones': 66,
  'Kansas Jayhawks': 2305,
  'Kansas State Wildcats': 2306,
  'Oklahoma State Cowboys': 197,
  'TCU Horned Frogs': 2628,
  'Texas Tech Red Raiders': 2641,
  'UCF Knights': 2116,
  'Utah Utes': 254,
  'West Virginia Mountaineers': 277,
  // ACC
  'Boston College Eagles': 103,
  'California Golden Bears': 25,
  'Clemson Tigers': 228,
  'Duke Blue Devils': 150,
  'Florida State Seminoles': 52,
  'Georgia Tech Yellow Jackets': 59,
  'Louisville Cardinals': 97,
  'Miami Hurricanes': 2390,
  'NC State Wolfpack': 152,
  'North Carolina Tar Heels': 153,
  'Pittsburgh Panthers': 221,
  'SMU Mustangs': 2567,
  'Stanford Cardinal': 24,
  'Syracuse Orange': 183,
  'Virginia Cavaliers': 258,
  'Virginia Tech Hokies': 259,
  'Wake Forest Demon Deacons': 154,
  // American Athletic Conference (AAC)
  'Charlotte 49ers': 2429,
  'East Carolina Pirates': 151,
  'FAU Owls': 2226,
  'Memphis Tigers': 235,
  'Navy Midshipmen': 2426,
  'North Texas Mean Green': 249,
  'Rice Owls': 242,
  'South Florida Bulls': 58,
  'Temple Owls': 218,
  'Tulane Green Wave': 2655,
  'Tulsa Golden Hurricane': 202,
  'UTSA Roadrunners': 2636,
  'Wichita State Shockers': 706,
  // Sun Belt
  'App State Mountaineers': 2026,
  'Arkansas State Red Wolves': 2032,
  'Coastal Carolina Chanticleers': 324,
  'Georgia Southern Eagles': 290,
  'Georgia State Panthers': 2247,
  'James Madison Dukes': 256,
  'Louisiana Ragin Cajuns': 309,
  'Louisiana Monroe Warhawks': 2433,
  'Marshall Thundering Herd': 276,
  'Old Dominion Monarchs': 295,
  'South Alabama Jaguars': 6,
  'Southern Miss Golden Eagles': 2572,
  'Texas State Bobcats': 326,
  'Troy Trojans': 2653,
  // Conference USA (C-USA)
  'FIU Panthers': 2229,
  'Jacksonville State Gamecocks': 55,
  'Kennesaw State Owls': 338,
  'Liberty Flames': 2335,
  'Louisiana Tech Bulldogs': 2348,
  'Middle Tennessee Blue Raiders': 2393,
  'New Mexico State Aggies': 166,
  'Sam Houston Bearkats': 2534,
  'UTEP Miners': 2638,
  'Western Kentucky Hilltoppers': 98,
  // MAC
  'Akron Zips': 2006,
  'Ball State Cardinals': 2050,
  'Bowling Green Falcons': 189,
  'Buffalo Bulls': 2084,
  'Central Michigan Chippewas': 2117,
  'Eastern Michigan Eagles': 2199,
  'Kent State Golden Flashes': 2309,
  'Miami (OH) RedHawks': 193,
  'Northern Illinois Huskies': 2459,
  'Ohio Bobcats': 195,
  'Toledo Rockets': 2649,
  'Western Michigan Broncos': 2711,
  // Mountain West
  'Air Force Falcons': 2005,
  'Boise State Broncos': 68,
  'Colorado State Rams': 36,
  'Fresno State Bulldogs': 278,
  'Hawaii Rainbow Warriors': 62,
  'Nevada Wolf Pack': 2440,
  'New Mexico Lobos': 167,
  'San Diego State Aztecs': 21,
  'San Jose State Spartans': 23,
  'UNLV Rebels': 2439,
  'Utah State Aggies': 328,
  'Wyoming Cowboys': 2751,
  // Independents
  'Notre Dame Fighting Irish': 87,
  'Army Black Knights': 349,
  'Connecticut Huskies': 41,
  'UMass Minutemen': 113,
};
